# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d3d127da04086a6f09a5e328709c0d8f2784c73d5e7df8c92b75844aaa88a343bc8aaad199a76a8fd16ce3dbbf3437af44332eda055caf9c8a6e8dd8766584b2

test:
  secret_key_base: e68e3935e4065be5722bb951c90c07b46d314b465fb6b1c348e22ff0e09f361a7f3c774c4d0ec966de0ebf0f9b97e5ea6a32f1f95ac7ac8cedd6586dc7d87aa6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
